def Menu():
    print("-" * 50)
    print("\tATM OR Funds Transfer Application")
    print("-" * 50)
    print("\t1. Deposit")
    print("\t2. Withdraw")
    print("\t3. Balance Enquiry")
    print("\t4. Create Customer")
    print("\t5. View Customer")
    print("\t6. View All Customers")
    print("\t7. Update Customer")
    print("\t8. Delete Customer")
    print("\t9. Exit")
    print("-" * 50)